SCR_MissionHeader {
 World "{68C1D284498EF91B}worlds/5mike.ent"
 m_sName "5mike Kolguyev"
 m_sIcon "{76A267381A5DEDF7}Assets/images/5mike.edds"
 m_sLoadingScreen "{76A267381A5DEDF7}Assets/images/5mike.edds"
 m_sPreviewImage "{76A267381A5DEDF7}Assets/images/5mike.edds"
 m_sGameMode "Scenario GameMode GameMaster"
 m_iPlayerCount 64
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bOverrideScenarioTimeAndWeather 1
 m_iStartingHours 12
 m_fDayTimeAcceleration 0.1
 m_fNightTimeAcceleration 0.1
 m_bMapMarkerEnableDeleteByAnyone 1
 m_iMapMarkerLimitPerPlayer 69
 m_bIsArmavisionAllowedInMP 1
}